# Generated by Django 2.2 on 2020-08-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200829_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_upload',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
