# Generated by Django 3.1.2 on 2020-10-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userdetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='register',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='first_name',
        ),
    ]
