# Generated by Django 3.0 on 2020-11-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201031_1719'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userdetails',
        ),
    ]
