# Generated by Django 3.0 on 2020-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20201103_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_upload',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
