# Generated by Django 3.0 on 2020-11-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20201104_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file_upload',
            field=models.TextField(blank=True, db_column='data'),
        ),
    ]
